### ISSUE TITLE
Add autoprefixer to project

### ISSUE THREAD

**Issue by morenoh149** [r3dm/temp#10]

**Comment by BerkeleyTrue** [comment]
Kouto-Swiss?

**Comment by morenoh149** [comment]
https://github.com/passy/autoprefixer-loader seems easiest

**Comment by BerkeleyTrue** [comment]
I feel like the world is pushing me away from browserify and to webpack... I can't seem to avoid it.

**Comment by morenoh149** [comment]
It's evil. Convenience will trump modularity unless we actively push against it. But I also want to finish the project as soon as possible.

**Comment by morenoh149** [comment]
seems like radium does vendor prefixing as well. https://github.com/FormidableLabs/radium/issues/11
